// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParfumAsistani.Data;

#nullable disable

namespace ParfumAsistani.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321101235_AddNotaAndParfumManyToMany")]
    partial class AddNotaAndParfumManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotaParfum", b =>
                {
                    b.Property<int>("NotalarId")
                        .HasColumnType("int");

                    b.Property<int>("ParfumlerId")
                        .HasColumnType("int");

                    b.HasKey("NotalarId", "ParfumlerId");

                    b.HasIndex("ParfumlerId");

                    b.ToTable("ParfumNota", (string)null);
                });

            modelBuilder.Entity("ParfumAsistani.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GorselUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Notalar", (string)null);
                });

            modelBuilder.Entity("ParfumAsistani.Models.Parfum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Parfumler", (string)null);
                });

            modelBuilder.Entity("NotaParfum", b =>
                {
                    b.HasOne("ParfumAsistani.Models.Nota", null)
                        .WithMany()
                        .HasForeignKey("NotalarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParfumAsistani.Models.Parfum", null)
                        .WithMany()
                        .HasForeignKey("ParfumlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
